---
---
{%- if jekyll.environment == "production" -%}

backend:
  name: git-gateway
  branch: decapcms

{%- else -%}

local_backend: true
backend:
  name: proxy
  proxy_url: http://192.168.0.141:8081/api/v1

{%- endif %}

media_folder: "assets/img"
site_url: {{ site.url }}
locale: ru
editor:
  preview: false
show_preview_links: false
collections:
- name: pages
  label: Текст на сайте
  files:
    - name: index
      label: Главная
      file: index.html
      fields:
        - { label: Фото, name: hero__photo, widget: file, allow_multiple: false}
        - { label: Заголовок, name: hero__heading, widget: string }
        - { label: Краткое описание, name: hero__tagline, widget: string }
    - name: pieces
      label: Мои пьесы
      file: pieces.html
      fields:
        - { label: Абзац 1, name: p1, widget: text }
        - { label: Абзац 2, name: p2, widget: text }
